name: 'my_real_estate_project'
version: '1.0.0'
config-version: 2

profile: 'my_real_estate_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]  # Keep this as-is for now
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_real_estate_project:
    raw:
      +materialized: ephemeral
    staging:
      +materialized: view
    marts:
      +materialized: table