-- models/01_raw/raw_buildings.sql

with filtered_buildings as (
    select
        id,
        street_address,
        street_address_alias,
        city,
        state,
        zip_code,
        lat,
        lon,
        msa,
        building_name,
        building_name_alias,
        building_phone_number,
        building_website,
        is_single_family,
        is_condo,
        is_apartment,
        number_units,
        year_built,
        number_stories,
        management_company,
        specials,
        cats_monthly_rent,
        cats_one_time_fee,
        cats_deposit,
        dogs_monthly_rent,
        dogs_one_time_fee,
        dogs_deposit,
        admin_fee,
        amenity_fee,
        application_fee,
        storage_fee,
        parking_covered,
        parking_garage,
        parking_surface_lot,
        listing_urls,
        created_on,
        image_gcs_file_names,
        lease_lengths,
        min_deposit,
        max_deposit,
        verified_listing,
        walk_score,
        transit_score,
        bike_score,
        point,
        user_id,
        avg_quality,
        estimated_occupancy,
        unit_mix_old,
        is_student,
        is_senior,
        point_v2,
        latest_unit_source,
        is_affordable,
        building_amenities,
        unit_amenities,
        is_lease_up,
        leased_percentage,
        exposure_percentage,
        google_place_id,
        photo_url,
        unit_mix,
        management_company_new,
        building_name_new,
        building_website_new,
        geog_point,

        -- Add row number for deduplication based on listing_urls
        row_number() over (
            partition by listing_urls
            order by created_on desc
        ) as row_num

    FROM {{ source('raw_data', 'hello_data_buildings_raw') }}
    WHERE
        state = 'UT'
        AND city IS NOT NULL
        AND street_address IS NOT NULL
        AND state IS NOT NULL
        AND lat IS NOT NULL
        AND lon IS NOT NULL
        AND zip_code IS NOT NULL
        AND msa IS NOT NULL
)

select
    id,
    street_address,
    street_address_alias,
    city,
    state,
    zip_code,
    lat,
    lon,
    msa,
    building_name,
    building_name_alias,
    building_phone_number,
    building_website,
    is_single_family,
    is_condo,
    is_apartment,
    number_units,
    year_built,
    number_stories,
    management_company,
    specials,
    cats_monthly_rent,
    cats_one_time_fee,
    cats_deposit,
    dogs_monthly_rent,
    dogs_one_time_fee,
    dogs_deposit,
    admin_fee,
    amenity_fee,
    application_fee,
    storage_fee,
    parking_covered,
    parking_garage,
    parking_surface_lot,
    listing_urls,
    created_on,
    image_gcs_file_names,
    lease_lengths,
    min_deposit,
    max_deposit,
    verified_listing,
    walk_score,
    transit_score,
    bike_score,
    point,
    user_id,
    avg_quality,
    estimated_occupancy,
    unit_mix_old,
    is_student,
    is_senior,
    point_v2,
    latest_unit_source,
    is_affordable,
    building_amenities,
    unit_amenities,
    is_lease_up,
    leased_percentage,
    exposure_percentage,
    google_place_id,
    photo_url,
    unit_mix,
    management_company_new,
    building_name_new,
    building_website_new,
    geog_point
from filtered_buildings
where row_num = 1
ORDER BY id
limit 10000