# models/01_raw/sources.yml
version: 2

sources:
  - name: raw_data
    description: >
      Raw data from external real estate sources including Hello Data API,
      Zillow property listings, and Landwatch property data.
      This schema contains unprocessed data before transformation.
    schema: public
    tables:
      - name: hello_data_buildings_raw
        description: >
          Raw building data from Hello Data API containing comprehensive 
          building characteristics, amenities, location data, and management 
          information for rental properties across multiple markets.
        columns:
          - name: id
            description: "Unique building identifier from Hello Data"
          - name: street_address
            description: "Physical street address of the building"
          - name: state
            description: "State abbreviation where building is located"
          - name: city
            description: "City where building is located"
          - name: zip_code
            description: "ZIP/postal code for building location"
          - name: lat
            description: "Latitude coordinate"
          - name: lon
            description: "Longitude coordinate"
          - name: building_name
            description: "Primary name of the building"
          - name: number_units
            description: "Total number of units in the building"
          - name: year_built
            description: "Year the building was constructed"
          - name: management_company
            description: "Property management company name"
          - name: created_on
            description: "Timestamp when record was created"
          - name: is_single_family
            description: "Boolean flag for single family homes"
          - name: is_condo
            description: "Boolean flag for condominium properties"
          - name: is_apartment
            description: "Boolean flag for apartment buildings"
          - name: walk_score
            description: "Walk Score rating (0-100) for walkability"
          - name: transit_score
            description: "Transit Score rating (0-100)"
          - name: bike_score
            description: "Bike Score rating (0-100)"

      - name: hello_data_units_raw
        description: >
          Raw unit-level data from Hello Data API including detailed unit 
          specifications, pricing information, availability status, and 
          unit-specific amenities for rental properties.
        columns:
          - name: id
            description: "Unique unit identifier from Hello Data"
          - name: building_id
            description: "Foreign key to hello_data_buildings_raw.id"
          - name: floorplan_name
            description: "Name/identifier of the floorplan"
          - name: unit_name
            description: "Specific unit identifier"
          - name: is_floorplan
            description: "Boolean indicating if record is floorplan vs specific unit"
          - name: availability
            description: "Current availability status"
          - name: price
            description: "Current unit price"
          - name: bed
            description: "Number of bedrooms"
          - name: bath
            description: "Number of full bathrooms"
          - name: sqft
            description: "Square footage of the unit"
          - name: created_on
            description: "Timestamp when record was created"
          - name: effective_price
            description: "Effective price after concessions"
          - name: _data_pipeline_only_state
            description: "State identifier (pipeline internal field)"

      - name: hello_data_units_history_raw
        description: >
          Historical time-series data for unit pricing and availability from Hello Data.
          Tracks changes in unit prices, availability status, effective pricing 
          with concessions, and lease terms over time.
        columns:
          - name: building_id
            description: "Foreign key to hello_data_buildings_raw.id"
          - name: unit_id
            description: "Foreign key to hello_data_units_raw.id"
          - name: price
            description: "Unit price during this period"
          - name: availability
            description: "Availability status during this period"
          - name: from_date
            description: "Start date for this pricing/availability period"
          - name: to_date
            description: "End date for this pricing/availability period"
          - name: effective_price
            description: "Effective price after concessions during this period"
          - name: period_id
            description: "Identifier for the time period"
          - name: lease_term
            description: "Lease terms available during this period"
          - name: _data_pipeline_only_state
            description: "State identifier (pipeline internal field)"

      - name: zillow_property_raw
        description: >
          Raw property listing data from Zillow including for-sale properties
          with comprehensive listing details, pricing history, market metrics,
          and property characteristics across multiple markets.
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: id
            description: "Unique property identifier from Zillow"
          - name: source_url
            description: "Zillow listing URL"
          - name: created_at
            description: "Timestamp when record was created in our system"
          - name: status
            description: "Current listing status"
          - name: price
            description: "Current listing price"
          - name: state
            description: "State abbreviation where property is located"
          - name: city
            description: "City where property is located"
          - name: latitude
            description: "Latitude coordinate"
          - name: longitude
            description: "Longitude coordinate"
          - name: bedrooms
            description: "Number of bedrooms"
          - name: bathrooms
            description: "Number of bathrooms"
          - name: living_area
            description: "Living area square footage"
          - name: year_built
            description: "Year property was built"
          - name: home_type
            description: "Type of home (house, condo, etc.)"
          - name: zestimate
            description: "Zillow's automated property value estimate"
          - name: days_on_zillow
            description: "Number of days listed on Zillow"
          - name: country
            description: "Country where property is located"

      - name: landwatch_properties_raw
        description: >
          Raw property and land listing data from Landwatch including 
          land sales, lot characteristics, pricing information, and 
          geographic details for properties across multiple markets.
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: id
            description: "Unique property identifier from Landwatch"
          - name: url
            description: "Landwatch listing URL"
          - name: created_at
            description: "Timestamp when record was created in our system"
          - name: name
            description: "Property name or title"
          - name: property_type
            description: "Type/category of the property"
          - name: price
            description: "Listed price of the property"
          - name: state
            description: "State abbreviation where property is located"
          - name: city
            description: "City where property is located"
          - name: zip
            description: "ZIP/postal code"
          - name: latitude
            description: "Latitude coordinate"
          - name: longitude
            description: "Longitude coordinate"
          - name: lot_size
            description: "Size of the lot"
          - name: lot_size_units
            description: "Units for lot size measurement"
          - name: acres
            description: "Lot size in acres"
          - name: address1
            description: "Primary address line"
          - name: county
            description: "County where property is located"
          - name: beds
            description: "Number of bedrooms (if applicable)"
          - name: baths
            description: "Number of bathrooms (if applicable)"
          - name: homesqft
            description: "Home square footage (if applicable)"
          - name: is_irrigated
            description: "Boolean flag for irrigation availability"
          - name: is_residence
            description: "Boolean flag indicating if property includes residence"
          - name: cost_per_acre
            description: "Calculated cost per acre"
          - name: distance_to_city_miles
            description: "Distance to city center in miles"

      - name: manual_collected_properties
        description: >
          Manually collected property data including address, coordinates,
          bedroom/bathroom counts, square footage, cost, and listing URLs
          for properties across various Utah locations.
        columns:
          - name: address
            description: "Full property address"
          - name: lat
            description: "Latitude coordinate"
          - name: lon
            description: "Longitude coordinate"
          - name: bed
            description: "Number of bedrooms"
          - name: bath
            description: "Number of bathrooms"
          - name: sqft
            description: "Property square footage"
          - name: cost
            description: "Property cost/price"
          - name: url
            description: "Property listing URL"

      - name: landwatch_urls
        description: >
          URL tracking table for Landwatch scraping operations including
          URL management, state information, scraping timestamps, and
          processing status for systematic data collection.
        columns:
          - name: url
            description: "Landwatch listing URL to be scraped"
          - name: state
            description: "State abbreviation for the property location"
          - name: scraped_at
            description: "Date when the URL was successfully scraped"
          - name: created_at
            description: "Timestamp when URL was added to tracking table"
          - name: last_pulled
            description: "Timestamp of last scraping attempt"
          - name: processing_id
            description: "Identifier for processing batch or job"

      - name: zillow_urls
        description: >
          URL tracking table for Zillow scraping operations including
          URL management, state and type information, scraping timestamps,
          and processing status for systematic data collection.
        columns:
          - name: url
            description: "Zillow listing URL to be scraped"
          - name: state
            description: "State abbreviation for the property location"
          - name: type
            description: "Type of Zillow listing (e.g., for_sale, for_rent)"
          - name: scraped_at
            description: "Date when the URL was successfully scraped"
          - name: created_at
            description: "Timestamp when URL was added to tracking table"
          - name: last_pulled
            description: "Timestamp of last scraping attempt"
          - name: processing_id
            description: "Identifier for processing batch or job"
