name: Deploy zillow scraper initializer

on:
  push:
    paths:
      - "**"
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: beta

      - name: Create temporary cloudbuild.yaml
        run: |
          cat > cloudbuild.yaml << EOF
          steps:
            - name: 'gcr.io/kaniko-project/executor:latest'
              args:
                - --dockerfile=Dockerfile
                - --destination=us-west3-docker.pkg.dev/flowing-flame-464314-j5/real-estate-location-selection/zillow-scraper:latest
                - --cache=true
                - --cache-repo=us-west3-docker.pkg.dev/flowing-flame-464314-j5/real-estate-location-selection/cache
                - --context=dir://.
                - --build-arg=SCRAPER_PATH=real_estate_location_selection/scrapers/zillow/run_zillow_job_initialization.py
          options:
            machineType: 'E2_HIGHCPU_8'
            diskSizeGb: 100
            logging: CLOUD_LOGGING_ONLY
          timeout: 1200s
          EOF

      - run: gcloud builds submit --config=cloudbuild.yaml