name: Deploy land watch scraper

on:
  push:
    paths:
      - "**"
    branches: [main]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: beta

      - run: gcloud config set builds/use_kaniko True

      - name: Create temporary cloudbuild.yaml
        run: |
          cat > cloudbuild.yaml << EOF
          steps:
            - name: 'gcr.io/cloud-builders/docker'
              args: [
                'build',
                '--build-arg', 'SCRAPER_PATH=real_estate_location_selection/scrapers/land_watch/run_land_watch_scraper.py',
                '-t', 'us-west3-docker.pkg.dev/flowing-flame-464314-j5/real-estate-location-selection/land-watch-scraper:latest',
                '.'
              ]
            - name: 'gcr.io/cloud-builders/docker'
              args: ['push', 'us-west3-docker.pkg.dev/flowing-flame-464314-j5/real-estate-location-selection/land-watch-scraper:latest']
          options:
            logging: CLOUD_LOGGING_ONLY
          EOF

      - run: gcloud builds submit --config=cloudbuild.yaml